name: rakuun_tech
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0
  flutter_highlight: ^0.7.0
  flutter_spinbox: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/icons/
    - assets/images/

  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/Inter.ttf
    - family: LeagueSpartan
      fonts: 
        - asset: assets/fonts/LeagueSpartan.ttf 