// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcqgnYA_3GNA2-fEX9C4PXPrfjn4IZYtc',
    appId: '1:693291003678:android:eff4bcab2a2750c5fbe30f',
    messagingSenderId: '693291003678',
    projectId: 'rakuun-tech-7cc89',
    databaseURL: 'https://rakuun-tech-7cc89-default-rtdb.firebaseio.com',
    storageBucket: 'rakuun-tech-7cc89.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOd6H6Q1gJH4FM_5HAKPXF3T_2I_9oCxg',
    appId: '1:693291003678:web:1626e560875cbeb4fbe30f',
    messagingSenderId: '693291003678',
    projectId: 'rakuun-tech-7cc89',
    authDomain: 'rakuun-tech-7cc89.firebaseapp.com',
    databaseURL: 'https://rakuun-tech-7cc89-default-rtdb.firebaseio.com',
    storageBucket: 'rakuun-tech-7cc89.firebasestorage.app',
  );
}
